"""Change type request_id to int

Revision ID: 91c9856309bd
Revises: a6f76b5673fa
Create Date: 2026-01-09 00:10:24.743754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c9856309bd'
down_revision: Union[str, Sequence[str], None] = 'a6f76b5673fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_orders', 'request_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='request_id::integer')
    op.drop_index(op.f('ix_service_orders_request_id'), table_name='service_orders')
    op.create_index(op.f('ix_service_orders_request_id'), 'service_orders', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_orders_request_id'), table_name='service_orders')
    op.create_index(op.f('ix_service_orders_request_id'), 'service_orders', ['request_id'], unique=True)
    op.alter_column('service_orders', 'request_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
