CREATE USER app_habi WITH PASSWORD '7slm59JUebyYZQ625vUJ';
CREATE DATABASE habi_db ENCODING 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';

GRANT ALL PRIVILEGES ON DATABASE habi_db TO app_habi;
ALTER USER app_habi SUPERUSER;

CREATE USER test_habi WITH PASSWORD 'MRc1VKa5aA0Z';
CREATE DATABASE habi_testdb ENCODING 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';

GRANT ALL PRIVILEGES ON DATABASE habi_testdb TO test_habi;
ALTER USER test_habi SUPERUSER;